# Generated by Django 4.1.5 on 2023-01-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_cover_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='commit',
            field=models.TextField(),
        ),
    ]
